// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: proto/chat.proto

package chatpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Chat_RegisterUser_FullMethodName        = "/chat.Chat/RegisterUser"
	Chat_SendOfflineMessages_FullMethodName = "/chat.Chat/SendOfflineMessages"
	Chat_GetMessageHistory_FullMethodName   = "/chat.Chat/GetMessageHistory"
	Chat_Chat_FullMethodName                = "/chat.Chat/Chat"
	Chat_CreateStream_FullMethodName        = "/chat.Chat/CreateStream"
	Chat_BroadcastMessage_FullMethodName    = "/chat.Chat/BroadcastMessage"
)

// ChatClient is the client API for Chat service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChatClient interface {
	RegisterUser(ctx context.Context, in *UserCredientials, opts ...grpc.CallOption) (*RegisterResponse, error)
	SendOfflineMessages(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ChatMessage, UploadSummary], error)
	GetMessageHistory(ctx context.Context, in *ChatHistoryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatMessage], error)
	Chat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ChatMessage, ChatMessage], error)
	CreateStream(ctx context.Context, in *Connect, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatMessage], error)
	BroadcastMessage(ctx context.Context, in *ChatMessage, opts ...grpc.CallOption) (*Close, error)
}

type chatClient struct {
	cc grpc.ClientConnInterface
}

func NewChatClient(cc grpc.ClientConnInterface) ChatClient {
	return &chatClient{cc}
}

func (c *chatClient) RegisterUser(ctx context.Context, in *UserCredientials, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, Chat_RegisterUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) SendOfflineMessages(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ChatMessage, UploadSummary], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Chat_ServiceDesc.Streams[0], Chat_SendOfflineMessages_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChatMessage, UploadSummary]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Chat_SendOfflineMessagesClient = grpc.ClientStreamingClient[ChatMessage, UploadSummary]

func (c *chatClient) GetMessageHistory(ctx context.Context, in *ChatHistoryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Chat_ServiceDesc.Streams[1], Chat_GetMessageHistory_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChatHistoryRequest, ChatMessage]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Chat_GetMessageHistoryClient = grpc.ServerStreamingClient[ChatMessage]

func (c *chatClient) Chat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ChatMessage, ChatMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Chat_ServiceDesc.Streams[2], Chat_Chat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChatMessage, ChatMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Chat_ChatClient = grpc.BidiStreamingClient[ChatMessage, ChatMessage]

func (c *chatClient) CreateStream(ctx context.Context, in *Connect, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Chat_ServiceDesc.Streams[3], Chat_CreateStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Connect, ChatMessage]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Chat_CreateStreamClient = grpc.ServerStreamingClient[ChatMessage]

func (c *chatClient) BroadcastMessage(ctx context.Context, in *ChatMessage, opts ...grpc.CallOption) (*Close, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Close)
	err := c.cc.Invoke(ctx, Chat_BroadcastMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatServer is the server API for Chat service.
// All implementations must embed UnimplementedChatServer
// for forward compatibility.
type ChatServer interface {
	RegisterUser(context.Context, *UserCredientials) (*RegisterResponse, error)
	SendOfflineMessages(grpc.ClientStreamingServer[ChatMessage, UploadSummary]) error
	GetMessageHistory(*ChatHistoryRequest, grpc.ServerStreamingServer[ChatMessage]) error
	Chat(grpc.BidiStreamingServer[ChatMessage, ChatMessage]) error
	CreateStream(*Connect, grpc.ServerStreamingServer[ChatMessage]) error
	BroadcastMessage(context.Context, *ChatMessage) (*Close, error)
	mustEmbedUnimplementedChatServer()
}

// UnimplementedChatServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChatServer struct{}

func (UnimplementedChatServer) RegisterUser(context.Context, *UserCredientials) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterUser not implemented")
}
func (UnimplementedChatServer) SendOfflineMessages(grpc.ClientStreamingServer[ChatMessage, UploadSummary]) error {
	return status.Error(codes.Unimplemented, "method SendOfflineMessages not implemented")
}
func (UnimplementedChatServer) GetMessageHistory(*ChatHistoryRequest, grpc.ServerStreamingServer[ChatMessage]) error {
	return status.Error(codes.Unimplemented, "method GetMessageHistory not implemented")
}
func (UnimplementedChatServer) Chat(grpc.BidiStreamingServer[ChatMessage, ChatMessage]) error {
	return status.Error(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedChatServer) CreateStream(*Connect, grpc.ServerStreamingServer[ChatMessage]) error {
	return status.Error(codes.Unimplemented, "method CreateStream not implemented")
}
func (UnimplementedChatServer) BroadcastMessage(context.Context, *ChatMessage) (*Close, error) {
	return nil, status.Error(codes.Unimplemented, "method BroadcastMessage not implemented")
}
func (UnimplementedChatServer) mustEmbedUnimplementedChatServer() {}
func (UnimplementedChatServer) testEmbeddedByValue()              {}

// UnsafeChatServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatServer will
// result in compilation errors.
type UnsafeChatServer interface {
	mustEmbedUnimplementedChatServer()
}

func RegisterChatServer(s grpc.ServiceRegistrar, srv ChatServer) {
	// If the following call panics, it indicates UnimplementedChatServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Chat_ServiceDesc, srv)
}

func _Chat_RegisterUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserCredientials)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).RegisterUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chat_RegisterUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).RegisterUser(ctx, req.(*UserCredientials))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_SendOfflineMessages_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChatServer).SendOfflineMessages(&grpc.GenericServerStream[ChatMessage, UploadSummary]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Chat_SendOfflineMessagesServer = grpc.ClientStreamingServer[ChatMessage, UploadSummary]

func _Chat_GetMessageHistory_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChatHistoryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChatServer).GetMessageHistory(m, &grpc.GenericServerStream[ChatHistoryRequest, ChatMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Chat_GetMessageHistoryServer = grpc.ServerStreamingServer[ChatMessage]

func _Chat_Chat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChatServer).Chat(&grpc.GenericServerStream[ChatMessage, ChatMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Chat_ChatServer = grpc.BidiStreamingServer[ChatMessage, ChatMessage]

func _Chat_CreateStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Connect)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChatServer).CreateStream(m, &grpc.GenericServerStream[Connect, ChatMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Chat_CreateStreamServer = grpc.ServerStreamingServer[ChatMessage]

func _Chat_BroadcastMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).BroadcastMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chat_BroadcastMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).BroadcastMessage(ctx, req.(*ChatMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// Chat_ServiceDesc is the grpc.ServiceDesc for Chat service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Chat_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chat.Chat",
	HandlerType: (*ChatServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterUser",
			Handler:    _Chat_RegisterUser_Handler,
		},
		{
			MethodName: "BroadcastMessage",
			Handler:    _Chat_BroadcastMessage_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendOfflineMessages",
			Handler:       _Chat_SendOfflineMessages_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "GetMessageHistory",
			Handler:       _Chat_GetMessageHistory_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Chat",
			Handler:       _Chat_Chat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "CreateStream",
			Handler:       _Chat_CreateStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/chat.proto",
}
